cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED INSTALL_ROOT)
    message(FATAL_ERROR "Set INSTALL_ROOT to the compiler contract installation")
endif()
set(vendor "${INSTALL_ROOT}/Infernux/_compiler/taichi/_vendor/taichi")
file(GLOB native "${vendor}/_lib/core/*compiler_contract*")
if(NOT native)
    message(FATAL_ERROR "Native compiler contract was not installed below the private namespace")
endif()
foreach(member __init__.py lang/kernel_impl.py types/buffer_type.py)
    if(NOT EXISTS "${vendor}/${member}")
        message(FATAL_ERROR "Missing private compiler member: ${member}")
    endif()
endforeach()
foreach(member ad algorithms aot examples graph linalg math profiler shaders simt sparse tools ui _snode _ti_module)
    if(EXISTS "${vendor}/${member}")
        message(FATAL_ERROR "Retired compiler directory was installed: ${member}")
    endif()
endforeach()
foreach(member LICENSE NOTICE)
    if(NOT EXISTS "${INSTALL_ROOT}/Infernux/_compiler/licenses/taichi/${member}")
        message(FATAL_ERROR "Missing upstream attribution: ${member}")
    endif()
endforeach()
if(EXISTS "${INSTALL_ROOT}/taichi" OR EXISTS "${INSTALL_ROOT}/python/taichi")
    message(FATAL_ERROR "Compiler installation leaked a public Taichi package")
endif()
message(STATUS "Private engine compiler installation contract passed")
